name: "build-and-release"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  ci:
    name: "Run tests"
    strategy:
      fail-fast: false
      matrix:
        python-version: [
#          "3.9.18",
          "3.10.13",
          "3.11.6",
          "3.12",
        ]
        poetry-version: ["1.6.1"]
        os: [
          ubuntu-latest,
          macos-latest,
#          windows-latest, # Disabling Windows to get build working
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install --all-extras
      - name: Run tests
        run: poetry run pytest

  tagged-release: # TODO: Maybe make this conditional so it can run on pull requests
    name: "Tagged Release"
    needs: ci
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.6.1'
      - name: Install dependencies
        run: | 
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry install --all-extras
      - name: Run tests
        run: poetry run pytest
#      - name: Create Github release
#        uses: "marvinpinto/action-automatic-releases@latest"
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          prerelease: false
#          files: |
#            dist/*.whl
#            dist/*.tar.gz
      - name: Build and publish package
        run: poetry publish --build --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
        continue-on-error: true
